/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Record({
  'status1' : IDL.Text,
  'status2' : IDL.Text,
  'status3' : IDL.Text,
  'status4' : IDL.Text,
  'status5' : IDL.Text,
  'status6' : IDL.Text,
  'status7' : IDL.Text,
  'status8' : IDL.Text,
  'status9' : IDL.Text,
  'status10' : IDL.Text,
  'status11' : IDL.Text,
  'status12' : IDL.Text,
  'status13' : IDL.Text,
  'status14' : IDL.Text,
  'status15' : IDL.Text,
  'status16' : IDL.Text,
  'status17' : IDL.Text,
  'status18' : IDL.Text,
  'status19' : IDL.Text,
  'status20' : IDL.Text,
  'status21' : IDL.Text,
  'orderId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpsertOrders' : IDL.Func([IDL.Vec(OrderStatus)], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderStatus)], ['query']),
  'getAppConfig' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderStatus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAppConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'upsertOrder' : IDL.Func([OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Record({
    'status1' : IDL.Text,
    'status2' : IDL.Text,
    'status3' : IDL.Text,
    'status4' : IDL.Text,
    'status5' : IDL.Text,
    'status6' : IDL.Text,
    'status7' : IDL.Text,
    'status8' : IDL.Text,
    'status9' : IDL.Text,
    'status10' : IDL.Text,
    'status11' : IDL.Text,
    'status12' : IDL.Text,
    'status13' : IDL.Text,
    'status14' : IDL.Text,
    'status15' : IDL.Text,
    'status16' : IDL.Text,
    'status17' : IDL.Text,
    'status18' : IDL.Text,
    'status19' : IDL.Text,
    'status20' : IDL.Text,
    'status21' : IDL.Text,
    'orderId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpsertOrders' : IDL.Func([IDL.Vec(OrderStatus)], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderStatus)], ['query']),
    'getAppConfig' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderStatus)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAppConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'upsertOrder' : IDL.Func([OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };